export const items = [
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وصف الافطار",
    price: "50",
    category: "فطار",
    imgUrl: "meal1.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة غداء",
    description: "وصف غداء",
    price: "50",
    category: "غداء",
    imgUrl: "meal1.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وصف الافطار",
    price: "50",
    category: "فطار",
    imgUrl: "meal1.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وصف الافطار",
    price: "50",
    category: "فطار",
    imgUrl: "meal1.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة غداء",
    description: "وصف غداء",
    price: "50",
    category: "غداء",
    imgUrl: "meal1.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة فطار",
    description: "وصف الافطار",
    price: "50",
    category: "فطار",
    imgUrl: "meal1.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة غداء",
    description: "وصف غداء",
    price: "50",
    category: "غداء",
    imgUrl: "meal1.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء",
    description: "وصف عشاء",
    price: "50",
    category: "عشاء",
    imgUrl: "meal1.jpg",
  },
  {
    id: Math.random(),
    title: "وجبة عشاء",
    description: " وصف عشاء درجه اولي",
    price: "50",
    category: "عشاء",
    imgUrl: "meal1.jpg",
  },
];
